# Generated by Django 4.0.1 on 2022-01-08 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Название компании')),
                ('unp', models.CharField(default='', max_length=300, verbose_name='УНП/ИНН')),
                ('description', models.CharField(blank=True, default='', max_length=2000, verbose_name='Описание')),
                ('country', models.CharField(default='', max_length=200, verbose_name='Страна')),
                ('city', models.CharField(default='', max_length=200, verbose_name='Город')),
                ('street', models.CharField(default='', max_length=200, verbose_name='Улица')),
                ('address', models.CharField(default='', max_length=200, verbose_name='Дом')),
                ('dop_address', models.CharField(blank=True, default='', max_length=200, verbose_name='Номер помещения')),
                ('phone', models.CharField(default='', max_length=200, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('site', models.CharField(blank=True, default='', max_length=200, verbose_name='Сайт')),
                ('telegram', models.CharField(blank=True, default='', max_length=200, verbose_name='Telegram')),
                ('viber', models.CharField(blank=True, default=' ', max_length=200, verbose_name='Viber')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=200, verbose_name='WhatsApp')),
                ('instagram', models.CharField(blank=True, default='', max_length=200, verbose_name='Instagram')),
                ('vk', models.CharField(blank=True, default='', max_length=200, verbose_name='VK')),
                ('ok', models.CharField(blank=True, default='', max_length=200, verbose_name='Одноклассники')),
                ('facebook', models.CharField(blank=True, default='', max_length=200, verbose_name='Facebook')),
                ('logo', models.ImageField(blank=True, default='static/img/logo_company/default.jpg', null=True, upload_to='static/img/logo_company', verbose_name='Логотип')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_companies', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='posts', to='company.Category')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='company.post')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_date'],
            },
        ),
    ]
