# Generated by Django 4.0.1 on 2022-01-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Описание'),
        ),
    ]
