# Generated by Django 4.0.1 on 2022-01-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_created_by_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='created_by',
        ),
    ]
