# Generated by Django 4.0.1 on 2022-01-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_post_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.ImageField(blank=True, default='img/logo_company/default.jpg', null=True, upload_to='img/logo_company', verbose_name='Логотип'),
        ),
    ]
